#!/bin/sh

# Set these paths appropriately

BIN="/home/jovyan/work/treetagger/bin"
CMD="/home/jovyan/work/treetagger/cmd"
LIB="/home/jovyan/work/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
