#!/bin/sh

# Set these paths appropriately

BIN="/home/jovyan/work/treetagger/bin"
CMD="/home/jovyan/work/treetagger/cmd"
LIB="/home/jovyan/work/treetagger/lib"

OPTIONS="-token -lemma -sgml -pt-with-lemma"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/german-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/german-spoken.par

$TOKENIZER -a $ABBR_LIST $* |
# tagging
$TAGGER $OPTIONS $PARFILE
