#!/bin/sh

# Set these paths appropriately

BIN="/home/jovyan/work/treetagger/bin"
CMD="/home/jovyan/work/treetagger/cmd"
LIB="/home/jovyan/work/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/latin-abbreviations
PARFILE=${LIB}/latin.par
MWLFILE=${LIB}/latin-mwls

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE

